/* Generated By:JavaCC: Do not edit this line. RustTokenManager.java */
package projeto_compilador_rust;

/** Token Manager. */
public class RustTokenManager implements RustConstants
{

  /** Debug output. */
  public static  java.io.PrintStream debugStream = System.out;
  /** Set debug output. */
  public static  void setDebugStream(java.io.PrintStream ds) { debugStream = ds; }
private static final int jjStopStringLiteralDfa_0(int pos, long active0, long active1)
{
   switch (pos)
   {
      case 0:
         if ((active1 & 0x40000000L) != 0L)
            return 12;
         if ((active0 & 0x100000102200000L) != 0L || (active1 & 0x8000L) != 0L)
         {
            jjmatchedKind = 102;
            return 6;
         }
         if ((active0 & 0xfcffe000fdd00000L) != 0L || (active1 & 0x3003dcf7f3fL) != 0L)
         {
            jjmatchedKind = 102;
            return 12;
         }
         if ((active1 & 0x2000000L) != 0L)
            return 9;
         if ((active0 & 0x200000000000000L) != 0L || (active1 & 0x3000c0L) != 0L)
         {
            jjmatchedKind = 102;
            return 2;
         }
         return -1;
      case 1:
         if ((active1 & 0x2000000L) != 0L)
            return 10;
         if ((active0 & 0xf4fe6001ddf00000L) != 0L || (active1 & 0x3003defbfbfL) != 0L)
         {
            if (jjmatchedPos != 1)
            {
               jjmatchedKind = 102;
               jjmatchedPos = 1;
            }
            return 12;
         }
         if ((active0 & 0x801800022000000L) != 0L || (active1 & 0x4000L) != 0L)
            return 12;
         if ((active0 & 0x100000000000000L) != 0L)
         {
            if (jjmatchedPos != 1)
            {
               jjmatchedKind = 102;
               jjmatchedPos = 1;
            }
            return 5;
         }
         if ((active0 & 0x200000000000000L) != 0L || (active1 & 0x100040L) != 0L)
         {
            if (jjmatchedPos != 1)
            {
               jjmatchedKind = 102;
               jjmatchedPos = 1;
            }
            return 1;
         }
         return -1;
      case 2:
         if ((active0 & 0xe04040010d300000L) != 0L || (active1 & 0x8112201L) != 0L)
            return 12;
         if ((active0 & 0x14bf2000d0c00000L) != 0L || (active1 & 0x30035ee9dfeL) != 0L)
         {
            if (jjmatchedPos != 2)
            {
               jjmatchedKind = 102;
               jjmatchedPos = 2;
            }
            return 12;
         }
         if ((active0 & 0x100000000000000L) != 0L)
         {
            if (jjmatchedPos != 2)
            {
               jjmatchedKind = 102;
               jjmatchedPos = 2;
            }
            return 4;
         }
         if ((active0 & 0x200000000000000L) != 0L)
         {
            if (jjmatchedPos != 2)
            {
               jjmatchedKind = 102;
               jjmatchedPos = 2;
            }
            return 21;
         }
         return -1;
      case 3:
         if ((active0 & 0x1600200040c00000L) != 0L || (active1 & 0x1028008cL) != 0L)
            return 12;
         if ((active0 & 0xbf400090000000L) != 0L || (active1 & 0x30025c69d72L) != 0L)
         {
            if (jjmatchedPos != 3)
            {
               jjmatchedKind = 102;
               jjmatchedPos = 3;
            }
            return 12;
         }
         if ((active0 & 0x100000000000000L) != 0L)
         {
            if (jjmatchedPos != 3)
            {
               jjmatchedKind = 102;
               jjmatchedPos = 3;
            }
            return 21;
         }
         return -1;
      case 4:
         if ((active0 & 0x90400000000000L) != 0L || (active1 & 0x30000e41912L) != 0L)
         {
            if (jjmatchedPos != 4)
            {
               jjmatchedKind = 102;
               jjmatchedPos = 4;
            }
            return 12;
         }
         if ((active0 & 0x12f000090000000L) != 0L || (active1 & 0x25028460L) != 0L)
            return 12;
         return -1;
      case 5:
         if ((active0 & 0x80400000000000L) != 0L || (active1 & 0x201112L) != 0L)
            return 12;
         if ((active0 & 0x10000000000000L) != 0L || (active1 & 0x30004c40800L) != 0L)
         {
            jjmatchedKind = 102;
            jjmatchedPos = 5;
            return 12;
         }
         return -1;
      case 6:
         if ((active1 & 0xc00000L) != 0L)
            return 12;
         if ((active0 & 0x10000000000000L) != 0L || (active1 & 0x30004040800L) != 0L)
         {
            jjmatchedKind = 102;
            jjmatchedPos = 6;
            return 12;
         }
         return -1;
      case 7:
         if ((active0 & 0x10000000000000L) != 0L || (active1 & 0x40800L) != 0L)
            return 12;
         if ((active1 & 0x20004000000L) != 0L)
         {
            jjmatchedKind = 102;
            jjmatchedPos = 7;
            return 12;
         }
         return -1;
      case 8:
         if ((active1 & 0x20004000000L) != 0L)
         {
            jjmatchedKind = 102;
            jjmatchedPos = 8;
            return 12;
         }
         return -1;
      case 9:
         if ((active1 & 0x4000000L) != 0L)
         {
            jjmatchedKind = 102;
            jjmatchedPos = 9;
            return 12;
         }
         return -1;
      default :
         return -1;
   }
}
private static final int jjStartNfa_0(int pos, long active0, long active1)
{
   return jjMoveNfa_0(jjStopStringLiteralDfa_0(pos, active0, active1), pos + 1);
}
static private int jjStopAtPos(int pos, int kind)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   return pos + 1;
}
static private int jjStartNfaWithStates_0(int pos, int kind, int state)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) { return pos + 1; }
   return jjMoveNfa_0(state, pos + 1);
}
static private int jjMoveStringLiteralDfa0_0()
{
   switch(curChar)
   {
      case 33:
         jjmatchedKind = 12;
         return jjMoveStringLiteralDfa1_0(0x4000L, 0x0L);
      case 37:
         return jjStopAtPos(0, 9);
      case 38:
         return jjMoveStringLiteralDfa1_0(0x400L, 0x0L);
      case 39:
         return jjMoveStringLiteralDfa1_0(0x0L, 0x2000000L);
      case 40:
         return jjStopAtPos(0, 39);
      case 41:
         return jjStopAtPos(0, 40);
      case 42:
         return jjStopAtPos(0, 7);
      case 43:
         return jjStopAtPos(0, 5);
      case 44:
         return jjStopAtPos(0, 41);
      case 45:
         jjmatchedKind = 6;
         return jjMoveStringLiteralDfa1_0(0x200000000L, 0x0L);
      case 46:
         jjmatchedKind = 19;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x80000000L);
      case 47:
         return jjStopAtPos(0, 8);
      case 58:
         jjmatchedKind = 36;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x100000000L);
      case 59:
         return jjStopAtPos(0, 35);
      case 60:
         jjmatchedKind = 15;
         return jjMoveStringLiteralDfa1_0(0x20000L, 0x0L);
      case 61:
         jjmatchedKind = 34;
         return jjMoveStringLiteralDfa1_0(0x40000002000L, 0x0L);
      case 62:
         jjmatchedKind = 16;
         return jjMoveStringLiteralDfa1_0(0x40000L, 0x0L);
      case 83:
         return jjMoveStringLiteralDfa1_0(0x0L, 0x8L);
      case 91:
         return jjStopAtPos(0, 43);
      case 93:
         return jjStopAtPos(0, 44);
      case 95:
         return jjStartNfaWithStates_0(0, 94, 12);
      case 97:
         return jjMoveStringLiteralDfa1_0(0x3800000000000L, 0x800L);
      case 98:
         return jjMoveStringLiteralDfa1_0(0x4000000400000L, 0x3000L);
      case 99:
         return jjMoveStringLiteralDfa1_0(0x38000000800000L, 0x0L);
      case 100:
         return jjMoveStringLiteralDfa1_0(0x40000000000000L, 0x4000L);
      case 101:
         return jjMoveStringLiteralDfa1_0(0x80200040000000L, 0x0L);
      case 102:
         return jjMoveStringLiteralDfa1_0(0x100000102200000L, 0x8000L);
      case 103:
         return jjMoveStringLiteralDfa1_0(0x0L, 0x10000L);
      case 105:
         return jjMoveStringLiteralDfa1_0(0xc00000020100000L, 0x0L);
      case 108:
         return jjMoveStringLiteralDfa1_0(0x1000000004000000L, 0x0L);
      case 109:
         return jjMoveStringLiteralDfa1_0(0x6000000018000000L, 0x4020000L);
      case 111:
         return jjMoveStringLiteralDfa1_0(0x0L, 0x40000L);
      case 112:
         return jjMoveStringLiteralDfa1_0(0x8000000000000000L, 0x10000080000L);
      case 114:
         return jjMoveStringLiteralDfa1_0(0x0L, 0x20008000003L);
      case 115:
         return jjMoveStringLiteralDfa1_0(0x400001000000L, 0x10000034L);
      case 116:
         return jjMoveStringLiteralDfa1_0(0x200000000000000L, 0x3000c0L);
      case 117:
         return jjMoveStringLiteralDfa1_0(0x0L, 0x20400300L);
      case 118:
         return jjMoveStringLiteralDfa1_0(0x0L, 0x800000L);
      case 119:
         return jjMoveStringLiteralDfa1_0(0x80000000L, 0x400L);
      case 121:
         return jjMoveStringLiteralDfa1_0(0x0L, 0x1000000L);
      case 123:
         return jjStopAtPos(0, 37);
      case 124:
         return jjMoveStringLiteralDfa1_0(0x800L, 0x0L);
      case 125:
         return jjStopAtPos(0, 38);
      default :
         return jjMoveNfa_0(3, 0);
   }
}
static private int jjMoveStringLiteralDfa1_0(long active0, long active1)
{
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(0, active0, active1);
      return 1;
   }
   switch(curChar)
   {
      case 38:
         if ((active0 & 0x400L) != 0L)
            return jjStopAtPos(1, 10);
         break;
      case 46:
         if ((active1 & 0x80000000L) != 0L)
            return jjStopAtPos(1, 95);
         break;
      case 51:
         return jjMoveStringLiteralDfa2_0(active0, 0x100000L, active1, 0L);
      case 54:
         return jjMoveStringLiteralDfa2_0(active0, 0x200000L, active1, 0L);
      case 58:
         if ((active1 & 0x100000000L) != 0L)
            return jjStopAtPos(1, 96);
         break;
      case 61:
         if ((active0 & 0x2000L) != 0L)
            return jjStopAtPos(1, 13);
         else if ((active0 & 0x4000L) != 0L)
            return jjStopAtPos(1, 14);
         else if ((active0 & 0x20000L) != 0L)
            return jjStopAtPos(1, 17);
         else if ((active0 & 0x40000L) != 0L)
            return jjStopAtPos(1, 18);
         break;
      case 62:
         if ((active0 & 0x200000000L) != 0L)
            return jjStopAtPos(1, 33);
         else if ((active0 & 0x40000000000L) != 0L)
            return jjStopAtPos(1, 42);
         break;
      case 97:
         return jjMoveStringLiteralDfa2_0(active0, 0x100000010000000L, active1, 0x1c020000L);
      case 98:
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0x800L);
      case 101:
         return jjMoveStringLiteralDfa2_0(active0, 0x4000000L, active1, 0x2000001100fL);
      case 102:
         if ((active0 & 0x20000000L) != 0L)
            return jjStartNfaWithStates_0(1, 29, 12);
         break;
      case 104:
         return jjMoveStringLiteralDfa2_0(active0, 0x80800000L, active1, 0x400L);
      case 105:
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0x1808000L);
      case 108:
         return jjMoveStringLiteralDfa2_0(active0, 0x40000000L, active1, 0L);
      case 109:
         return jjMoveStringLiteralDfa2_0(active0, 0x400000000000000L, active1, 0L);
      case 110:
         if ((active0 & 0x2000000L) != 0L)
            return jjStartNfaWithStates_0(1, 25, 12);
         else if ((active0 & 0x800000000000000L) != 0L)
            return jjStartNfaWithStates_0(1, 59, 12);
         return jjMoveStringLiteralDfa2_0(active0, 0x200000000000L, active1, 0x20400100L);
      case 111:
         if ((active1 & 0x4000L) != 0L)
            return jjStartNfaWithStates_0(1, 78, 12);
         return jjMoveStringLiteralDfa2_0(active0, 0x7018000100400000L, active1, 0x2000L);
      case 114:
         return jjMoveStringLiteralDfa2_0(active0, 0x224000000000000L, active1, 0x10000180040L);
      case 115:
         if ((active0 & 0x800000000000L) != 0L)
         {
            jjmatchedKind = 47;
            jjmatchedPos = 1;
         }
         return jjMoveStringLiteralDfa2_0(active0, 0x1000000000000L, active1, 0x2000200L);
      case 116:
         return jjMoveStringLiteralDfa2_0(active0, 0x400001000000L, active1, 0x10L);
      case 117:
         return jjMoveStringLiteralDfa2_0(active0, 0x8000000008000000L, active1, 0x20L);
      case 118:
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0x40000L);
      case 119:
         return jjMoveStringLiteralDfa2_0(active0, 0x2000000000000L, active1, 0L);
      case 120:
         return jjMoveStringLiteralDfa2_0(active0, 0x80000000000000L, active1, 0L);
      case 121:
         return jjMoveStringLiteralDfa2_0(active0, 0x40000000000000L, active1, 0x200080L);
      case 124:
         if ((active0 & 0x800L) != 0L)
            return jjStopAtPos(1, 11);
         break;
      default :
         break;
   }
   return jjStartNfa_0(0, active0, active1);
}
static private int jjMoveStringLiteralDfa2_0(long old0, long active0, long old1, long active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(0, old0, old1); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(1, active0, active1);
      return 2;
   }
   switch(curChar)
   {
      case 50:
         if ((active0 & 0x100000L) != 0L)
            return jjStartNfaWithStates_0(2, 20, 12);
         break;
      case 52:
         if ((active0 & 0x200000L) != 0L)
            return jjStartNfaWithStates_0(2, 21, 12);
         break;
      case 97:
         return jjMoveStringLiteralDfa3_0(active0, 0x22000000800000L, active1, 0x20000000050L);
      case 98:
         if ((active0 & 0x8000000000000000L) != 0L)
            return jjStartNfaWithStates_0(2, 63, 12);
         break;
      case 99:
         return jjMoveStringLiteralDfa3_0(active0, 0L, active1, 0x4021000L);
      case 100:
         if ((active0 & 0x2000000000000000L) != 0L)
            return jjStartNfaWithStates_0(2, 61, 12);
         break;
      case 101:
         if ((active1 & 0x200L) != 0L)
            return jjStartNfaWithStates_0(2, 73, 12);
         return jjMoveStringLiteralDfa3_0(active0, 0x4000000000000L, active1, 0x1040400L);
      case 102:
         if ((active1 & 0x1L) != 0L)
            return jjStartNfaWithStates_0(2, 64, 12);
         return jjMoveStringLiteralDfa3_0(active0, 0L, active1, 0x10000000L);
      case 105:
         return jjMoveStringLiteralDfa3_0(active0, 0x80000000L, active1, 0x10020080000L);
      case 108:
         return jjMoveStringLiteralDfa3_0(active0, 0x100000000000000L, active1, 0xcL);
      case 110:
         if ((active0 & 0x40000000000000L) != 0L)
            return jjStartNfaWithStates_0(2, 54, 12);
         else if ((active1 & 0x10000L) != 0L)
            return jjStartNfaWithStates_0(2, 80, 12);
         return jjMoveStringLiteralDfa3_0(active0, 0x18000000000000L, active1, 0x8000L);
      case 111:
         return jjMoveStringLiteralDfa3_0(active0, 0x1000000000400000L, active1, 0L);
      case 112:
         return jjMoveStringLiteralDfa3_0(active0, 0x400000000000000L, active1, 0x2000a0L);
      case 114:
         if ((active0 & 0x1000000L) != 0L)
         {
            jjmatchedKind = 24;
            jjmatchedPos = 2;
         }
         else if ((active0 & 0x100000000L) != 0L)
            return jjStartNfaWithStates_0(2, 32, 12);
         return jjMoveStringLiteralDfa3_0(active0, 0x400000000000L, active1, 0x800000L);
      case 115:
         return jjMoveStringLiteralDfa3_0(active0, 0x40000000L, active1, 0x400900L);
      case 116:
         if ((active0 & 0x4000000L) != 0L)
            return jjStartNfaWithStates_0(2, 26, 12);
         else if ((active0 & 0x8000000L) != 0L)
            return jjStartNfaWithStates_0(2, 27, 12);
         return jjMoveStringLiteralDfa3_0(active0, 0x80000010000000L, active1, 0x2000002L);
      case 117:
         return jjMoveStringLiteralDfa3_0(active0, 0x200200000000000L, active1, 0L);
      case 118:
         if ((active0 & 0x4000000000000000L) != 0L)
            return jjStartNfaWithStates_0(2, 62, 12);
         break;
      case 119:
         if ((active1 & 0x8000000L) != 0L)
            return jjStartNfaWithStates_0(2, 91, 12);
         break;
      case 120:
         if ((active1 & 0x2000L) != 0L)
            return jjStartNfaWithStates_0(2, 77, 12);
         break;
      case 121:
         if ((active1 & 0x100000L) != 0L)
            return jjStartNfaWithStates_0(2, 84, 12);
         return jjMoveStringLiteralDfa3_0(active0, 0x1000000000000L, active1, 0L);
      default :
         break;
   }
   return jjStartNfa_0(1, active0, active1);
}
static private int jjMoveStringLiteralDfa3_0(long old0, long active0, long old1, long active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(1, old0, old1); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(2, active0, active1);
      return 3;
   }
   switch(curChar)
   {
      case 97:
         return jjMoveStringLiteralDfa4_0(active0, 0x4000000000000L, active1, 0x2008100L);
      case 99:
         return jjMoveStringLiteralDfa4_0(active0, 0x10000000L, active1, 0L);
      case 100:
         return jjMoveStringLiteralDfa4_0(active0, 0L, active1, 0x20000000000L);
      case 101:
         if ((active0 & 0x40000000L) != 0L)
            return jjStartNfaWithStates_0(3, 30, 12);
         else if ((active0 & 0x200000000000000L) != 0L)
            return jjStartNfaWithStates_0(3, 57, 12);
         else if ((active1 & 0x80L) != 0L)
         {
            jjmatchedKind = 71;
            jjmatchedPos = 3;
         }
         else if ((active1 & 0x10000000L) != 0L)
            return jjStartNfaWithStates_0(3, 92, 12);
         return jjMoveStringLiteralDfa4_0(active0, 0x80000000000000L, active1, 0x200020L);
      case 102:
         if ((active1 & 0x4L) != 0L)
            return jjStartNfaWithStates_0(3, 66, 12);
         else if ((active1 & 0x8L) != 0L)
            return jjStartNfaWithStates_0(3, 67, 12);
         break;
      case 105:
         return jjMoveStringLiteralDfa4_0(active0, 0x2000000000000L, active1, 0x400040L);
      case 108:
         if ((active0 & 0x400000L) != 0L)
            return jjStartNfaWithStates_0(3, 22, 12);
         else if ((active0 & 0x400000000000000L) != 0L)
            return jjStartNfaWithStates_0(3, 58, 12);
         return jjMoveStringLiteralDfa4_0(active0, 0x80000000L, active1, 0x1000000L);
      case 109:
         if ((active0 & 0x200000000000L) != 0L)
            return jjStartNfaWithStates_0(3, 45, 12);
         break;
      case 110:
         return jjMoveStringLiteralDfa4_0(active0, 0x1000000000000L, active1, 0x10000000000L);
      case 111:
         return jjMoveStringLiteralDfa4_0(active0, 0L, active1, 0x20001000L);
      case 112:
         if ((active0 & 0x1000000000000000L) != 0L)
            return jjStartNfaWithStates_0(3, 60, 12);
         break;
      case 114:
         if ((active0 & 0x800000L) != 0L)
            return jjStartNfaWithStates_0(3, 23, 12);
         return jjMoveStringLiteralDfa4_0(active0, 0L, active1, 0x4060400L);
      case 115:
         return jjMoveStringLiteralDfa4_0(active0, 0x108000000000000L, active1, 0L);
      case 116:
         return jjMoveStringLiteralDfa4_0(active0, 0x30000000000000L, active1, 0x800810L);
      case 117:
         return jjMoveStringLiteralDfa4_0(active0, 0x400000000000L, active1, 0x2L);
      case 118:
         if ((active1 & 0x80000L) != 0L)
            return jjStartNfaWithStates_0(3, 83, 12);
         break;
      default :
         break;
   }
   return jjStartNfa_0(2, active0, active1);
}
static private int jjMoveStringLiteralDfa4_0(long old0, long active0, long old1, long active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(2, old0, old1); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(3, active0, active1);
      return 4;
   }
   switch(curChar)
   {
      case 95:
         return jjMoveStringLiteralDfa5_0(active0, 0L, active1, 0x20000000000L);
      case 99:
         if ((active0 & 0x1000000000000L) != 0L)
            return jjStartNfaWithStates_0(4, 48, 12);
         return jjMoveStringLiteralDfa5_0(active0, 0x400000000000L, active1, 0L);
      case 100:
         if ((active1 & 0x1000000L) != 0L)
            return jjStartNfaWithStates_0(4, 88, 12);
         break;
      case 101:
         if ((active0 & 0x80000000L) != 0L)
            return jjStartNfaWithStates_0(4, 31, 12);
         else if ((active0 & 0x20000000000000L) != 0L)
            return jjStartNfaWithStates_0(4, 53, 12);
         else if ((active0 & 0x100000000000000L) != 0L)
            return jjStartNfaWithStates_0(4, 56, 12);
         else if ((active1 & 0x400L) != 0L)
            return jjStartNfaWithStates_0(4, 74, 12);
         break;
      case 102:
         return jjMoveStringLiteralDfa5_0(active0, 0L, active1, 0x100L);
      case 104:
         if ((active0 & 0x10000000L) != 0L)
            return jjStartNfaWithStates_0(4, 28, 12);
         break;
      case 105:
         return jjMoveStringLiteralDfa5_0(active0, 0x10000000000000L, active1, 0x10L);
      case 107:
         if ((active0 & 0x4000000000000L) != 0L)
            return jjStartNfaWithStates_0(4, 50, 12);
         break;
      case 108:
         if ((active1 & 0x8000L) != 0L)
            return jjStartNfaWithStates_0(4, 79, 12);
         break;
      case 109:
         return jjMoveStringLiteralDfa5_0(active0, 0L, active1, 0x1000L);
      case 110:
         if ((active1 & 0x20000000L) != 0L)
            return jjStartNfaWithStates_0(4, 93, 12);
         break;
      case 111:
         if ((active1 & 0x20000L) != 0L)
         {
            jjmatchedKind = 81;
            jjmatchedPos = 4;
         }
         return jjMoveStringLiteralDfa5_0(active0, 0L, active1, 0x4200000L);
      case 114:
         if ((active1 & 0x20L) != 0L)
            return jjStartNfaWithStates_0(4, 69, 12);
         return jjMoveStringLiteralDfa5_0(active0, 0x80000000000000L, active1, 0x40802L);
      case 116:
         if ((active0 & 0x2000000000000L) != 0L)
            return jjStartNfaWithStates_0(4, 49, 12);
         else if ((active0 & 0x8000000000000L) != 0L)
            return jjStartNfaWithStates_0(4, 51, 12);
         else if ((active1 & 0x40L) != 0L)
            return jjStartNfaWithStates_0(4, 70, 12);
         return jjMoveStringLiteralDfa5_0(active0, 0L, active1, 0x10002000000L);
      case 117:
         return jjMoveStringLiteralDfa5_0(active0, 0L, active1, 0x800000L);
      case 122:
         return jjMoveStringLiteralDfa5_0(active0, 0L, active1, 0x400000L);
      default :
         break;
   }
   return jjStartNfa_0(3, active0, active1);
}
static private int jjMoveStringLiteralDfa5_0(long old0, long active0, long old1, long active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(3, old0, old1); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(4, active0, active1);
      return 5;
   }
   switch(curChar)
   {
      case 95:
         return jjMoveStringLiteralDfa6_0(active0, 0L, active1, 0x4000000L);
      case 97:
         return jjMoveStringLiteralDfa6_0(active0, 0L, active1, 0x800800L);
      case 99:
         if ((active1 & 0x10L) != 0L)
            return jjStartNfaWithStates_0(5, 68, 12);
         break;
      case 101:
         if ((active1 & 0x100L) != 0L)
            return jjStartNfaWithStates_0(5, 72, 12);
         else if ((active1 & 0x1000L) != 0L)
            return jjStartNfaWithStates_0(5, 76, 12);
         return jjMoveStringLiteralDfa6_0(active0, 0L, active1, 0x400000L);
      case 102:
         if ((active1 & 0x200000L) != 0L)
            return jjStartNfaWithStates_0(5, 85, 12);
         break;
      case 105:
         return jjMoveStringLiteralDfa6_0(active0, 0L, active1, 0x2040000L);
      case 108:
         return jjMoveStringLiteralDfa6_0(active0, 0L, active1, 0x30000000000L);
      case 110:
         if ((active0 & 0x80000000000000L) != 0L)
            return jjStartNfaWithStates_0(5, 55, 12);
         else if ((active1 & 0x2L) != 0L)
            return jjStartNfaWithStates_0(5, 65, 12);
         return jjMoveStringLiteralDfa6_0(active0, 0x10000000000000L, active1, 0L);
      case 116:
         if ((active0 & 0x400000000000L) != 0L)
            return jjStartNfaWithStates_0(5, 46, 12);
         break;
      default :
         break;
   }
   return jjStartNfa_0(4, active0, active1);
}
static private int jjMoveStringLiteralDfa6_0(long old0, long active0, long old1, long active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(4, old0, old1); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(5, active0, active1);
      return 6;
   }
   switch(curChar)
   {
      case 99:
         if ((active1 & 0x2000000L) != 0L)
            return jjStopAtPos(6, 89);
         return jjMoveStringLiteralDfa7_0(active0, 0L, active1, 0x800L);
      case 100:
         if ((active1 & 0x400000L) != 0L)
            return jjStartNfaWithStates_0(6, 86, 12);
         return jjMoveStringLiteralDfa7_0(active0, 0L, active1, 0x40000L);
      case 105:
         return jjMoveStringLiteralDfa7_0(active0, 0L, active1, 0x20000000000L);
      case 108:
         if ((active1 & 0x800000L) != 0L)
            return jjStartNfaWithStates_0(6, 87, 12);
         break;
      case 110:
         return jjMoveStringLiteralDfa7_0(active0, 0L, active1, 0x10000000000L);
      case 114:
         return jjMoveStringLiteralDfa7_0(active0, 0L, active1, 0x4000000L);
      case 117:
         return jjMoveStringLiteralDfa7_0(active0, 0x10000000000000L, active1, 0L);
      default :
         break;
   }
   return jjStartNfa_0(5, active0, active1);
}
static private int jjMoveStringLiteralDfa7_0(long old0, long active0, long old1, long active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(5, old0, old1); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(6, active0, active1);
      return 7;
   }
   switch(curChar)
   {
      case 33:
         if ((active1 & 0x10000000000L) != 0L)
            return jjStopAtPos(7, 104);
         break;
      case 101:
         if ((active0 & 0x10000000000000L) != 0L)
            return jjStartNfaWithStates_0(7, 52, 12);
         else if ((active1 & 0x40000L) != 0L)
            return jjStartNfaWithStates_0(7, 82, 12);
         break;
      case 110:
         return jjMoveStringLiteralDfa8_0(active0, 0L, active1, 0x20000000000L);
      case 116:
         if ((active1 & 0x800L) != 0L)
            return jjStartNfaWithStates_0(7, 75, 12);
         break;
      case 117:
         return jjMoveStringLiteralDfa8_0(active0, 0L, active1, 0x4000000L);
      default :
         break;
   }
   return jjStartNfa_0(6, active0, active1);
}
static private int jjMoveStringLiteralDfa8_0(long old0, long active0, long old1, long active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(6, old0, old1); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(7, 0L, active1);
      return 8;
   }
   switch(curChar)
   {
      case 101:
         return jjMoveStringLiteralDfa9_0(active1, 0x20000000000L);
      case 108:
         return jjMoveStringLiteralDfa9_0(active1, 0x4000000L);
      default :
         break;
   }
   return jjStartNfa_0(7, 0L, active1);
}
static private int jjMoveStringLiteralDfa9_0(long old1, long active1)
{
   if (((active1 &= old1)) == 0L)
      return jjStartNfa_0(7, 0L, old1); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(8, 0L, active1);
      return 9;
   }
   switch(curChar)
   {
      case 33:
         if ((active1 & 0x20000000000L) != 0L)
            return jjStopAtPos(9, 105);
         break;
      case 101:
         return jjMoveStringLiteralDfa10_0(active1, 0x4000000L);
      default :
         break;
   }
   return jjStartNfa_0(8, 0L, active1);
}
static private int jjMoveStringLiteralDfa10_0(long old1, long active1)
{
   if (((active1 &= old1)) == 0L)
      return jjStartNfa_0(8, 0L, old1); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(9, 0L, active1);
      return 10;
   }
   switch(curChar)
   {
      case 115:
         if ((active1 & 0x4000000L) != 0L)
            return jjStartNfaWithStates_0(10, 90, 12);
         break;
      default :
         break;
   }
   return jjStartNfa_0(9, 0L, active1);
}
static final long[] jjbitVec0 = {
   0x0L, 0x0L, 0xffffffffffffffffL, 0xffffffffffffffffL
};
static private int jjMoveNfa_0(int startState, int curPos)
{
   //int[] nextStates; // not used
   int startsAt = 0;
   jjnewStateCnt = 21;
   int i = 1;
   jjstateSet[0] = startState;
   //int j; // not used
   int kind = 0x7fffffff;
   for (;;)
   {
      if (++jjround == 0x7fffffff)
         ReInitRounds();
      if (curChar < 64)
      {
         long l = 1L << curChar;
         do
         {
            switch(jjstateSet[--i])
            {
               case 3:
                  if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 97)
                        kind = 97;
                     jjCheckNAddStates(0, 2);
                  }
                  else if (curChar == 34)
                     jjCheckNAddTwoStates(14, 15);
                  else if (curChar == 39)
                     jjstateSet[jjnewStateCnt++] = 9;
                  break;
               case 4:
               case 12:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 102)
                     kind = 102;
                  jjCheckNAdd(12);
                  break;
               case 6:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 102)
                     kind = 102;
                  jjCheckNAdd(12);
                  break;
               case 5:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 102)
                     kind = 102;
                  jjCheckNAdd(12);
                  break;
               case 2:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 102)
                     kind = 102;
                  jjCheckNAdd(12);
                  break;
               case 1:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 102)
                     kind = 102;
                  jjCheckNAdd(12);
                  break;
               case 21:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 102)
                     kind = 102;
                  jjCheckNAdd(12);
                  break;
               case 8:
                  if (curChar == 39)
                     jjstateSet[jjnewStateCnt++] = 9;
                  break;
               case 9:
                  if ((0xffffff7fffffdbffL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 10;
                  break;
               case 10:
                  if (curChar == 39 && kind > 100)
                     kind = 100;
                  break;
               case 13:
                  if (curChar == 34)
                     jjCheckNAddTwoStates(14, 15);
                  break;
               case 14:
                  if ((0xfffffffbffffdbffL & l) != 0L)
                     jjCheckNAddTwoStates(14, 15);
                  break;
               case 15:
                  if (curChar == 34 && kind > 103)
                     kind = 103;
                  break;
               case 16:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 97)
                     kind = 97;
                  jjCheckNAddStates(0, 2);
                  break;
               case 17:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 97)
                     kind = 97;
                  jjCheckNAdd(17);
                  break;
               case 18:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(18, 19);
                  break;
               case 19:
                  if (curChar == 46)
                     jjCheckNAdd(20);
                  break;
               case 20:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 98)
                     kind = 98;
                  jjCheckNAdd(20);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else if (curChar < 128)
      {
         long l = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 3:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 102)
                        kind = 102;
                     jjCheckNAdd(12);
                  }
                  if (curChar == 102)
                     jjstateSet[jjnewStateCnt++] = 6;
                  else if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 2;
                  break;
               case 4:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 102)
                        kind = 102;
                     jjCheckNAdd(12);
                  }
                  if (curChar == 115)
                     jjCheckNAdd(0);
                  break;
               case 6:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 102)
                        kind = 102;
                     jjCheckNAdd(12);
                  }
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 5;
                  break;
               case 5:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 102)
                        kind = 102;
                     jjCheckNAdd(12);
                  }
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 4;
                  break;
               case 2:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 102)
                        kind = 102;
                     jjCheckNAdd(12);
                  }
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 1;
                  break;
               case 1:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 102)
                        kind = 102;
                     jjCheckNAdd(12);
                  }
                  if (curChar == 117)
                     jjCheckNAdd(0);
                  break;
               case 21:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 102)
                        kind = 102;
                     jjCheckNAdd(12);
                  }
                  if (curChar == 101)
                  {
                     if (kind > 99)
                        kind = 99;
                  }
                  break;
               case 0:
                  if (curChar == 101 && kind > 99)
                     kind = 99;
                  break;
               case 7:
                  if (curChar == 102)
                     jjstateSet[jjnewStateCnt++] = 6;
                  break;
               case 9:
                  jjstateSet[jjnewStateCnt++] = 10;
                  break;
               case 11:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 102)
                     kind = 102;
                  jjCheckNAdd(12);
                  break;
               case 12:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 102)
                     kind = 102;
                  jjCheckNAdd(12);
                  break;
               case 14:
                  jjAddStates(3, 4);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else
      {
         int i2 = (curChar & 0xff) >> 6;
         long l2 = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 9:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     jjstateSet[jjnewStateCnt++] = 10;
                  break;
               case 14:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     jjAddStates(3, 4);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      if (kind != 0x7fffffff)
      {
         jjmatchedKind = kind;
         jjmatchedPos = curPos;
         kind = 0x7fffffff;
      }
      ++curPos;
      if ((i = jjnewStateCnt) == (startsAt = 21 - (jjnewStateCnt = startsAt)))
         return curPos;
      try { curChar = input_stream.readChar(); }
      catch(java.io.IOException e) { return curPos; }
   }
}
static final int[] jjnextStates = {
   17, 18, 19, 14, 15, 
};

/** Token literal values. */
public static final String[] jjstrLiteralImages = {
"", null, null, null, null, "\53", "\55", "\52", "\57", "\45", "\46\46", 
"\174\174", "\41", "\75\75", "\41\75", "\74", "\76", "\74\75", "\76\75", "\56", 
"\151\63\62", "\146\66\64", "\142\157\157\154", "\143\150\141\162", "\163\164\162", 
"\146\156", "\154\145\164", "\155\165\164", "\155\141\164\143\150", "\151\146", 
"\145\154\163\145", "\167\150\151\154\145", "\146\157\162", "\55\76", "\75", "\73", "\72", "\173", 
"\175", "\50", "\51", "\54", "\75\76", "\133", "\135", "\145\156\165\155", 
"\163\164\162\165\143\164", "\141\163", "\141\163\171\156\143", "\141\167\141\151\164", 
"\142\162\145\141\153", "\143\157\156\163\164", "\143\157\156\164\151\156\165\145", 
"\143\162\141\164\145", "\144\171\156", "\145\170\164\145\162\156", "\146\141\154\163\145", 
"\164\162\165\145", "\151\155\160\154", "\151\156", "\154\157\157\160", "\155\157\144", 
"\155\157\166", "\160\165\142", "\162\145\146", "\162\145\164\165\162\156", 
"\163\145\154\146", "\123\145\154\146", "\163\164\141\164\151\143", "\163\165\160\145\162", 
"\164\162\141\151\164", "\164\171\160\145", "\165\156\163\141\146\145", "\165\163\145", 
"\167\150\145\162\145", "\141\142\163\164\162\141\143\164", "\142\145\143\157\155\145", 
"\142\157\170", "\144\157", "\146\151\156\141\154", "\147\145\156", "\155\141\143\162\157", 
"\157\166\145\162\162\151\144\145", "\160\162\151\166", "\164\162\171", "\164\171\160\145\157\146", 
"\165\156\163\151\172\145\144", "\166\151\162\164\165\141\154", "\171\151\145\154\144", 
"\47\163\164\141\164\151\143", "\155\141\143\162\157\137\162\165\154\145\163", "\162\141\167", 
"\163\141\146\145", "\165\156\151\157\156", "\137", "\56\56", "\72\72", null, null, null, null, 
null, null, null, "\160\162\151\156\164\154\156\41", 
"\162\145\141\144\137\154\151\156\145\41", };

/** Lexer state names. */
public static final String[] lexStateNames = {
   "DEFAULT", 
};
static final long[] jjtoToken = {
   0xffffffffffffffe1L, 0x3dfffffffffL, 
};
static final long[] jjtoSkip = {
   0x1eL, 0x0L, 
};
static protected SimpleCharStream input_stream;
static private final int[] jjrounds = new int[21];
static private final int[] jjstateSet = new int[42];
static protected char curChar;
/** Constructor. */
public RustTokenManager(SimpleCharStream stream){
   if (input_stream != null)
      throw new TokenMgrError("ERROR: Second call to constructor of static lexer. You must use ReInit() to initialize the static variables.", TokenMgrError.STATIC_LEXER_ERROR);
   input_stream = stream;
}

/** Constructor. */
public RustTokenManager(SimpleCharStream stream, int lexState){
   this(stream);
   SwitchTo(lexState);
}

/** Reinitialise parser. */
static public void ReInit(SimpleCharStream stream)
{
   jjmatchedPos = jjnewStateCnt = 0;
   curLexState = defaultLexState;
   input_stream = stream;
   ReInitRounds();
}
static private void ReInitRounds()
{
   int i;
   jjround = 0x80000001;
   for (i = 21; i-- > 0;)
      jjrounds[i] = 0x80000000;
}

/** Reinitialise parser. */
static public void ReInit(SimpleCharStream stream, int lexState)
{
   ReInit(stream);
   SwitchTo(lexState);
}

/** Switch to specified lex state. */
static public void SwitchTo(int lexState)
{
   if (lexState >= 1 || lexState < 0)
      throw new TokenMgrError("Error: Ignoring invalid lexical state : " + lexState + ". State unchanged.", TokenMgrError.INVALID_LEXICAL_STATE);
   else
      curLexState = lexState;
}

static protected Token jjFillToken()
{
   final Token t;
   final String tokenImage;
   final int beginLine;
   final int endLine;
   final int beginColumn;
   final int endColumn;
   String im = jjstrLiteralImages[jjmatchedKind];
   tokenImage = (im == null) ? input_stream.GetImage() : im;
   beginLine = input_stream.getBeginLine();
   beginColumn = input_stream.getBeginColumn();
   endLine = input_stream.getEndLine();
   endColumn = input_stream.getEndColumn();
   t = Token.newToken(jjmatchedKind, tokenImage);

   t.beginLine = beginLine;
   t.endLine = endLine;
   t.beginColumn = beginColumn;
   t.endColumn = endColumn;

   return t;
}

static int curLexState = 0;
static int defaultLexState = 0;
static int jjnewStateCnt;
static int jjround;
static int jjmatchedPos;
static int jjmatchedKind;

/** Get the next Token. */
public static Token getNextToken() 
{
  //int kind;
  Token specialToken = null;
  Token matchedToken;
  int curPos = 0;

  EOFLoop :
  for (;;)
  {   
   try   
   {     
      curChar = input_stream.BeginToken();
   }     
   catch(java.io.IOException e)
   {        
      jjmatchedKind = 0;
      matchedToken = jjFillToken();
      return matchedToken;
   }

   try { input_stream.backup(0);
      while (curChar <= 32 && (0x100002600L & (1L << curChar)) != 0L)
         curChar = input_stream.BeginToken();
   }
   catch (java.io.IOException e1) { continue EOFLoop; }
   jjmatchedKind = 0x7fffffff;
   jjmatchedPos = 0;
   curPos = jjMoveStringLiteralDfa0_0();
   if (jjmatchedKind != 0x7fffffff)
   {
      if (jjmatchedPos + 1 < curPos)
         input_stream.backup(curPos - jjmatchedPos - 1);
      if ((jjtoToken[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
      {
         matchedToken = jjFillToken();
         return matchedToken;
      }
      else
      {
         continue EOFLoop;
      }
   }
   int error_line = input_stream.getEndLine();
   int error_column = input_stream.getEndColumn();
   String error_after = null;
   boolean EOFSeen = false;
   try { input_stream.readChar(); input_stream.backup(1); }
   catch (java.io.IOException e1) {
      EOFSeen = true;
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
      if (curChar == '\n' || curChar == '\r') {
         error_line++;
         error_column = 0;
      }
      else
         error_column++;
   }
   if (!EOFSeen) {
      input_stream.backup(1);
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
   }
   throw new TokenMgrError(EOFSeen, curLexState, error_line, error_column, error_after, curChar, TokenMgrError.LEXICAL_ERROR);
  }
}

static private void jjCheckNAdd(int state)
{
   if (jjrounds[state] != jjround)
   {
      jjstateSet[jjnewStateCnt++] = state;
      jjrounds[state] = jjround;
   }
}
static private void jjAddStates(int start, int end)
{
   do {
      jjstateSet[jjnewStateCnt++] = jjnextStates[start];
   } while (start++ != end);
}
static private void jjCheckNAddTwoStates(int state1, int state2)
{
   jjCheckNAdd(state1);
   jjCheckNAdd(state2);
}

static private void jjCheckNAddStates(int start, int end)
{
   do {
      jjCheckNAdd(jjnextStates[start]);
   } while (start++ != end);
}

}
