/* Generated By:JavaCC: Do not edit this line. Rust.java */
package projeto_compilador_rust;

public class Rust implements RustConstants {
  public static void main(String args []) throws ParseException
  {
    Rust parser = new Rust(System.in);
    System.out.println("Compilador Rust carregado. Digite o codigo:");
    try
    {
      parser.Start();
      System.out.println("Analise Sintatica e L\u00e9xica: OK.");
    }
    catch (Exception e)
    {
      System.out.println("Erro Sintatico: " + e.getMessage());
    }
    catch (Error e)
    {
      System.out.println("Erro: " + e.getMessage());
    }
  }

/* REGRA DE ENTRADA PRINCIPAL */
/* Exemplo: fn soma(a: i32, b: i32) -> i32 { a + b } */
  static final public void Start() throws ParseException {
    label_1:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case FN:
      case ENUM:
      case STRUCT:
      case CONST:
      case MOD:
      case USE:
        ;
        break;
      default:
        jj_la1[0] = jj_gen;
        break label_1;
      }
      Item();
    }
    jj_consume_token(0);
  }

/* Exemplo: println!("Ola"); */
/* Exemplo: read_line!(nome); */
  static final public void EntradaSaida() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case PRINT:
      jj_consume_token(PRINT);
      jj_consume_token(LPAREN);
      Expressao();
      jj_consume_token(RPAREN);
      jj_consume_token(SEMICOLON);
      break;
    case READ:
      jj_consume_token(READ);
      jj_consume_token(LPAREN);
      jj_consume_token(IDENTIFIER);
      jj_consume_token(RPAREN);
      jj_consume_token(SEMICOLON);
      break;
    default:
      jj_la1[1] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

/* IMPORTAÇÃO E MÓDULOS */
/* Exemplo: mod utils { fn dobro(x: i32) -> i32 { x * 2 } } */
  static final public void module_declaration() throws ParseException {
    jj_consume_token(MOD);
    jj_consume_token(IDENTIFIER);
    jj_consume_token(LBRACE);
    label_2:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case FN:
      case ENUM:
      case STRUCT:
      case CONST:
      case MOD:
      case USE:
        ;
        break;
      default:
        jj_la1[2] = jj_gen;
        break label_2;
      }
      Item();
    }
    jj_consume_token(RBRACE);
  }

/* Exemplo: fn main() { ... } | struct Pessoa { idade: i32 } | use std::io; */
  static final public void Item() throws ParseException {
    if (jj_2_1(2)) {
      Funcao();
    } else if (jj_2_2(2)) {
      StructDef();
    } else if (jj_2_3(2)) {
      EnumDef();
    } else if (jj_2_4(2)) {
      module_declaration();
    } else {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case USE:
        use_imports();
        break;
      case CONST:
        DeclaracaoConst();
        break;
      default:
        jj_la1[3] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
  }

  static final public void modules_import() throws ParseException {
    jj_consume_token(MOD);
    jj_consume_token(IDENTIFIER);
  }

/* Exemplo: use std::io; */
  static final public void use_imports() throws ParseException {
    jj_consume_token(USE);
    path_set();
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case LBRACE:
    case IDENTIFIER:
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case LBRACE:
        jj_consume_token(LBRACE);
        label_3:
        while (true) {
          switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
          case IDENTIFIER:
            ;
            break;
          default:
            jj_la1[4] = jj_gen;
            break label_3;
          }
          jj_consume_token(IDENTIFIER);
          switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
          case COMMA:
            jj_consume_token(COMMA);
            break;
          default:
            jj_la1[5] = jj_gen;
            ;
          }
        }
        jj_consume_token(RBRACE);
        break;
      case IDENTIFIER:
        jj_consume_token(IDENTIFIER);
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case AS:
          jj_consume_token(AS);
          jj_consume_token(IDENTIFIER);
          break;
        default:
          jj_la1[6] = jj_gen;
          ;
        }
        break;
      default:
        jj_la1[7] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      break;
    default:
      jj_la1[8] = jj_gen;
      ;
    }
    jj_consume_token(SEMICOLON);
  }

  static final public void direct_import_full_path() throws ParseException {
    path_set();
    jj_consume_token(IDENTIFIER);
    jj_consume_token(LPAREN);
    jj_consume_token(RPAREN);
  }

  static final public void path_set() throws ParseException {
    jj_consume_token(IDENTIFIER);
    label_4:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case PATH_SEPARATOR:
        ;
        break;
      default:
        jj_la1[9] = jj_gen;
        break label_4;
      }
      jj_consume_token(PATH_SEPARATOR);
      jj_consume_token(IDENTIFIER);
    }
  }

/* Fluxo de controle : regras adaptadas para a interface do parser global. */

/* Exemplo: if x > 0 { 1 } else { 2 } | while x < 10 { x = x + 1; } */
  static final public void EstruturaControle() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case IF:
      IfStmt();
      break;
    case WHILE:
      WhileStmt();
      break;
    case LOOP:
      LoopStmt();
      break;
    case FOR:
      ForStmt();
      break;
    case MATCH:
      MatchStmt();
      break;
    default:
      jj_la1[10] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

/* Exemplo: if condicao { 1 } else if outra { 2 } else { 3 } */
  static final public void IfStmt() throws ParseException {
    jj_consume_token(IF);
    Expressao();
    Bloco();
    label_5:
    while (true) {
      if (jj_2_5(2)) {
        ;
      } else {
        break label_5;
      }
      jj_consume_token(ELSE);
      jj_consume_token(IF);
      Expressao();
      Bloco();
    }
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case ELSE:
      jj_consume_token(ELSE);
      Bloco();
      break;
    default:
      jj_la1[11] = jj_gen;
      ;
    }
  }

/* Exemplo: while x < 10 { x = x + 1; } */
  static final public void WhileStmt() throws ParseException {
    jj_consume_token(WHILE);
    Expressao();
    Bloco();
  }

/* Exemplo: loop { contador = contador + 1; } */
  static final public void LoopStmt() throws ParseException {
    jj_consume_token(LOOP);
    Bloco();
  }

/* Exemplo: for i in 0..10 { println!(i); } */
  static final public void ForStmt() throws ParseException {
    jj_consume_token(FOR);
    jj_consume_token(IDENTIFIER);
    jj_consume_token(IN);
    Iteravel();
    Bloco();
  }

/* Exemplo: match opcao { 1 => "Sim", _ => "Nao" } */
  static final public void MatchStmt() throws ParseException {
    jj_consume_token(MATCH);
    Expressao();
    jj_consume_token(LBRACE);
    label_6:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case FALSE:
      case TRUE:
      case UNDERSCORE:
      case CONSTANT:
      case BOOLEAN_LITERAL:
      case IDENTIFIER:
      case STRING_LITERAL:
        ;
        break;
      default:
        jj_la1[12] = jj_gen;
        break label_6;
      }
      MatchArm();
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case COMMA:
        jj_consume_token(COMMA);
        break;
      default:
        jj_la1[13] = jj_gen;
        ;
      }
    }
    jj_consume_token(RBRACE);
  }

/* Exemplo: 1 => "Sim" */
  static final public void MatchArm() throws ParseException {
    Pattern();
    jj_consume_token(FAT_ARROW);
    MatchBody();
  }

/* Exemplo: _ | 1 | "texto" | true */
  static final public void Pattern() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case CONSTANT:
      jj_consume_token(CONSTANT);
      break;
    case BOOLEAN_LITERAL:
      jj_consume_token(BOOLEAN_LITERAL);
      break;
    case TRUE:
      jj_consume_token(TRUE);
      break;
    case FALSE:
      jj_consume_token(FALSE);
      break;
    case IDENTIFIER:
      jj_consume_token(IDENTIFIER);
      break;
    case STRING_LITERAL:
      jj_consume_token(STRING_LITERAL);
      break;
    case UNDERSCORE:
      jj_consume_token(UNDERSCORE);
      break;
    default:
      jj_la1[14] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

/* Exemplo: { x + 1 } | "Sim" | resultado + 1 */
  static final public void MatchBody() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case LBRACE:
      Bloco();
      break;
    case STRING_LITERAL:
      jj_consume_token(STRING_LITERAL);
      break;
    case MINUS:
    case NOT:
    case MATCH:
    case IF:
    case LPAREN:
    case LBRACK:
    case FALSE:
    case TRUE:
    case CONSTANT:
    case FLOAT_LITERAL:
    case BOOLEAN_LITERAL:
    case CHAR_LITERAL:
    case IDENTIFIER:
      Expressao();
      break;
    default:
      jj_la1[15] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

/* Exemplo: 0..10 | lista */
  static final public void Iteravel() throws ParseException {
    Expressao();
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case DOTDOT:
      jj_consume_token(DOTDOT);
      Expressao();
      break;
    default:
      jj_la1[16] = jj_gen;
      ;
    }
  }

/* Wrappers temporarios para integrar o bloco de controle antes da chegada do Start(). */

/* Exemplo: { let x = 5; x + 1 } */
  static final public void Bloco() throws ParseException {
    jj_consume_token(LBRACE);
    label_7:
    while (true) {
      if (jj_2_6(2)) {
        ;
      } else {
        break label_7;
      }
      Comando();
    }
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case MINUS:
    case NOT:
    case MATCH:
    case IF:
    case LPAREN:
    case LBRACK:
    case FALSE:
    case TRUE:
    case CONSTANT:
    case FLOAT_LITERAL:
    case BOOLEAN_LITERAL:
    case CHAR_LITERAL:
    case IDENTIFIER:
    case STRING_LITERAL:
      Expressao();
      break;
    default:
      jj_la1[17] = jj_gen;
      ;
    }
    jj_consume_token(RBRACE);
  }

/* Exemplo: let x: i32 = 5; */
  static final public void DeclaracaoVar() throws ParseException {
    jj_consume_token(LET);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case MUT:
      jj_consume_token(MUT);
      break;
    default:
      jj_la1[18] = jj_gen;
      ;
    }
    jj_consume_token(IDENTIFIER);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case COLON:
      jj_consume_token(COLON);
      Tipo();
      break;
    default:
      jj_la1[19] = jj_gen;
      ;
    }
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case ASSIGN:
      jj_consume_token(ASSIGN);
      Expressao();
      break;
    default:
      jj_la1[20] = jj_gen;
      ;
    }
    jj_consume_token(SEMICOLON);
  }

/* Exemplo: const LIMITE: i32 = 10; */
  static final public void DeclaracaoConst() throws ParseException {
    jj_consume_token(CONST);
    jj_consume_token(IDENTIFIER);
    jj_consume_token(COLON);
    Tipo();
    jj_consume_token(ASSIGN);
    Expressao();
    jj_consume_token(SEMICOLON);
  }

/* Exemplo: let x = 5; | if x > 0 { 1 } else { 2 } | soma(a, b); */
  static final public void Comando() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case LET:
      DeclaracaoVar();
      break;
    case CONST:
      DeclaracaoConst();
      break;
    case MATCH:
    case IF:
    case WHILE:
    case FOR:
    case LOOP:
      EstruturaControle();
      break;
    default:
      jj_la1[21] = jj_gen;
      if (jj_2_7(2)) {
        EntradaSaida();
      } else {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case MINUS:
        case NOT:
        case MATCH:
        case IF:
        case LPAREN:
        case LBRACK:
        case FALSE:
        case TRUE:
        case CONSTANT:
        case FLOAT_LITERAL:
        case BOOLEAN_LITERAL:
        case CHAR_LITERAL:
        case IDENTIFIER:
        case STRING_LITERAL:
          Expressao();
          jj_consume_token(SEMICOLON);
          break;
        default:
          jj_la1[22] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
    }
  }

/*  Tipos  */

/* Exemplo: i32 | (i32, bool) | [i32; 10] */
  static final public void Tipo() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case I32:
    case F64:
    case BOOL:
    case CHAR_T:
    case STR_T:
      TipoPrim();
      break;
    case LPAREN:
      jj_consume_token(LPAREN);
      Tipo();
      label_8:
      while (true) {
        jj_consume_token(COMMA);
        Tipo();
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case COMMA:
          ;
          break;
        default:
          jj_la1[23] = jj_gen;
          break label_8;
        }
      }
      jj_consume_token(RPAREN);
      break;
    case LBRACK:
      jj_consume_token(LBRACK);
      Tipo();
      jj_consume_token(SEMICOLON);
      jj_consume_token(CONSTANT);
      jj_consume_token(RBRACK);
      break;
    default:
      jj_la1[24] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  static final public void TipoPrim() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case I32:
      jj_consume_token(I32);
      break;
    case F64:
      jj_consume_token(F64);
      break;
    case BOOL:
      jj_consume_token(BOOL);
      break;
    case CHAR_T:
      jj_consume_token(CHAR_T);
      break;
    case STR_T:
      jj_consume_token(STR_T);
      break;
    default:
      jj_la1[25] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

/*  Funcoes, Structs e Enums  */

/* Exemplo: fn soma(a: i32, b: i32) -> i32 { a + b } */
  static final public void Funcao() throws ParseException {
    jj_consume_token(FN);
    jj_consume_token(IDENTIFIER);
    jj_consume_token(LPAREN);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case IDENTIFIER:
      Parametros();
      break;
    default:
      jj_la1[26] = jj_gen;
      ;
    }
    jj_consume_token(RPAREN);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case ARROW:
      jj_consume_token(ARROW);
      Tipo();
      break;
    default:
      jj_la1[27] = jj_gen;
      ;
    }
    Bloco();
  }

/* Exemplo: a: i32, b: i32 */
  static final public void Parametros() throws ParseException {
    Parametro();
    label_9:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case COMMA:
        ;
        break;
      default:
        jj_la1[28] = jj_gen;
        break label_9;
      }
      jj_consume_token(COMMA);
      Parametro();
    }
  }

/* Exemplo: id: i32 */
  static final public void Parametro() throws ParseException {
    jj_consume_token(IDENTIFIER);
    jj_consume_token(COLON);
    Tipo();
  }

/* Exemplo: struct Pessoa { nome: str, idade: i32 } */
  static final public void StructDef() throws ParseException {
    jj_consume_token(STRUCT);
    jj_consume_token(IDENTIFIER);
    jj_consume_token(LBRACE);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case IDENTIFIER:
      CamposStruct();
      break;
    default:
      jj_la1[29] = jj_gen;
      ;
    }
    jj_consume_token(RBRACE);
  }

/* Exemplo: nome: str, idade: i32, */
  static final public void CamposStruct() throws ParseException {
    CampoStruct();
    label_10:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case COMMA:
        ;
        break;
      default:
        jj_la1[30] = jj_gen;
        break label_10;
      }
      jj_consume_token(COMMA);
      CampoStruct();
    }
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case COMMA:
      jj_consume_token(COMMA);
      break;
    default:
      jj_la1[31] = jj_gen;
      ;
    }
  }

/* Exemplo: idade: i32 */
  static final public void CampoStruct() throws ParseException {
    jj_consume_token(IDENTIFIER);
    jj_consume_token(COLON);
    Tipo();
  }

/* Exemplo: enum Cor { Vermelho, Verde, Azul } */
  static final public void EnumDef() throws ParseException {
    jj_consume_token(ENUM);
    jj_consume_token(IDENTIFIER);
    jj_consume_token(LBRACE);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case IDENTIFIER:
      VariantesEnum();
      break;
    default:
      jj_la1[32] = jj_gen;
      ;
    }
    jj_consume_token(RBRACE);
  }

/* Exemplo: Vermelho, Verde, Azul, */
  static final public void VariantesEnum() throws ParseException {
    jj_consume_token(IDENTIFIER);
    label_11:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case COMMA:
        ;
        break;
      default:
        jj_la1[33] = jj_gen;
        break label_11;
      }
      jj_consume_token(COMMA);
      jj_consume_token(IDENTIFIER);
    }
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case COMMA:
      jj_consume_token(COMMA);
      break;
    default:
      jj_la1[34] = jj_gen;
      ;
    }
  }

/* Exemplo: a + b * 2 > 10 && ativo */
  static final public void Expressao() throws ParseException {
    Atribuicao();
  }

  static final public void Atribuicao() throws ParseException {
    if (jj_2_8(2)) {
      jj_consume_token(IDENTIFIER);
      jj_consume_token(ASSIGN);
      Atribuicao();
    } else {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case MINUS:
      case NOT:
      case MATCH:
      case IF:
      case LPAREN:
      case LBRACK:
      case FALSE:
      case TRUE:
      case CONSTANT:
      case FLOAT_LITERAL:
      case BOOLEAN_LITERAL:
      case CHAR_LITERAL:
      case IDENTIFIER:
      case STRING_LITERAL:
        ExpressaoLogicaOr();
        break;
      default:
        jj_la1[35] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
  }

/* 1: or lógico (||) */
  static final public void ExpressaoLogicaOr() throws ParseException {
    ExpressaoLogicaAnd();
    label_12:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case OR:
        ;
        break;
      default:
        jj_la1[36] = jj_gen;
        break label_12;
      }
      jj_consume_token(OR);
      ExpressaoLogicaAnd();
    }
  }

/* 2: and logico (&&) */
  static final public void ExpressaoLogicaAnd() throws ParseException {
    ExpressaoIgualdade();
    label_13:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case AND:
        ;
        break;
      default:
        jj_la1[37] = jj_gen;
        break label_13;
      }
      jj_consume_token(AND);
      ExpressaoIgualdade();
    }
  }

/* 3: igualdade (==, !=) */
  static final public void ExpressaoIgualdade() throws ParseException {
    ExpressaoRelacional();
    label_14:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case EQ:
      case NEQ:
        ;
        break;
      default:
        jj_la1[38] = jj_gen;
        break label_14;
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case EQ:
        jj_consume_token(EQ);
        break;
      case NEQ:
        jj_consume_token(NEQ);
        break;
      default:
        jj_la1[39] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      ExpressaoRelacional();
    }
  }

/* 4: relacional (<, >, <=, >=) */
  static final public void ExpressaoRelacional() throws ParseException {
    ExpressaoAditiva();
    label_15:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case LT:
      case GT:
      case LE:
      case GE:
        ;
        break;
      default:
        jj_la1[40] = jj_gen;
        break label_15;
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case LT:
        jj_consume_token(LT);
        break;
      case GT:
        jj_consume_token(GT);
        break;
      case LE:
        jj_consume_token(LE);
        break;
      case GE:
        jj_consume_token(GE);
        break;
      default:
        jj_la1[41] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      ExpressaoAditiva();
    }
  }

/* 5: adição e Subtração (+, -) */
  static final public void ExpressaoAditiva() throws ParseException {
    ExpressaoMultiplicativa();
    label_16:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case PLUS:
      case MINUS:
        ;
        break;
      default:
        jj_la1[42] = jj_gen;
        break label_16;
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case PLUS:
        jj_consume_token(PLUS);
        break;
      case MINUS:
        jj_consume_token(MINUS);
        break;
      default:
        jj_la1[43] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      ExpressaoMultiplicativa();
    }
  }

/* Precedência 6: Multiplicação, Divisão e Módulo (*, /, %) */
  static final public void ExpressaoMultiplicativa() throws ParseException {
    ExpressaoUnaria();
    label_17:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case MULTIPLY:
      case DIVIDE:
      case MODULO:
        ;
        break;
      default:
        jj_la1[44] = jj_gen;
        break label_17;
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case MULTIPLY:
        jj_consume_token(MULTIPLY);
        break;
      case DIVIDE:
        jj_consume_token(DIVIDE);
        break;
      case MODULO:
        jj_consume_token(MODULO);
        break;
      default:
        jj_la1[45] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      ExpressaoUnaria();
    }
  }

/* 7: operadores unários (!verdadeiro, -numero) */
  static final public void ExpressaoUnaria() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case MINUS:
    case NOT:
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case MINUS:
        jj_consume_token(MINUS);
        break;
      case NOT:
        jj_consume_token(NOT);
        break;
      default:
        jj_la1[46] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      ExpressaoUnaria();
      break;
    case MATCH:
    case IF:
    case LPAREN:
    case LBRACK:
    case FALSE:
    case TRUE:
    case CONSTANT:
    case FLOAT_LITERAL:
    case BOOLEAN_LITERAL:
    case CHAR_LITERAL:
    case IDENTIFIER:
    case STRING_LITERAL:
      ExpressaoAcessoOuChamada();
      break;
    default:
      jj_la1[47] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

/* Exemplo: soma(a, b) | pessoa.nome | lista.push(x) */
  static final public void ExpressaoAcessoOuChamada() throws ParseException {
    FatorBase();
    label_18:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case DOT:
      case LPAREN:
        ;
        break;
      default:
        jj_la1[48] = jj_gen;
        break label_18;
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case LPAREN:
        jj_consume_token(LPAREN);
        ListaArgumentos();
        jj_consume_token(RPAREN);
        break;
      case DOT:
        jj_consume_token(DOT);
        jj_consume_token(IDENTIFIER);
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case LPAREN:
          jj_consume_token(LPAREN);
          ListaArgumentos();
          jj_consume_token(RPAREN);
          break;
        default:
          jj_la1[49] = jj_gen;
          ;
        }
        break;
      default:
        jj_la1[50] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
  }

/* Exemplo: 10 | nome | if ok { 1 } else { 2 } | match x { _ => 0 } | [1, 2] */
  static final public void FatorBase() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case FALSE:
    case TRUE:
    case CONSTANT:
    case FLOAT_LITERAL:
    case BOOLEAN_LITERAL:
    case CHAR_LITERAL:
    case STRING_LITERAL:
      Literal();
      break;
    case IDENTIFIER:
      jj_consume_token(IDENTIFIER);
      break;
    default:
      jj_la1[52] = jj_gen;
      if (jj_2_9(2)) {
        IfStmt();
      } else {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case MATCH:
          MatchStmt();
          break;
        default:
          jj_la1[53] = jj_gen;
          if (jj_2_10(3)) {
            jj_consume_token(LPAREN);
            Expressao();
            label_19:
            while (true) {
              jj_consume_token(COMMA);
              Expressao();
              switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
              case COMMA:
                ;
                break;
              default:
                jj_la1[51] = jj_gen;
                break label_19;
              }
            }
            jj_consume_token(RPAREN);
          } else {
            switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
            case LPAREN:
              jj_consume_token(LPAREN);
              Expressao();
              jj_consume_token(RPAREN);
              break;
            case LBRACK:
              ArrayLiteral();
              break;
            default:
              jj_la1[54] = jj_gen;
              jj_consume_token(-1);
              throw new ParseException();
            }
          }
        }
      }
    }
  }

  static final public void Literal() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case CONSTANT:
      jj_consume_token(CONSTANT);
      break;
    case FLOAT_LITERAL:
      jj_consume_token(FLOAT_LITERAL);
      break;
    case BOOLEAN_LITERAL:
      jj_consume_token(BOOLEAN_LITERAL);
      break;
    case TRUE:
      jj_consume_token(TRUE);
      break;
    case FALSE:
      jj_consume_token(FALSE);
      break;
    case CHAR_LITERAL:
      jj_consume_token(CHAR_LITERAL);
      break;
    case STRING_LITERAL:
      jj_consume_token(STRING_LITERAL);
      break;
    default:
      jj_la1[55] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  static final public void ArrayLiteral() throws ParseException {
    jj_consume_token(LBRACK);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case MINUS:
    case NOT:
    case MATCH:
    case IF:
    case LPAREN:
    case LBRACK:
    case FALSE:
    case TRUE:
    case CONSTANT:
    case FLOAT_LITERAL:
    case BOOLEAN_LITERAL:
    case CHAR_LITERAL:
    case IDENTIFIER:
    case STRING_LITERAL:
      ListaExpressoes();
      break;
    default:
      jj_la1[56] = jj_gen;
      ;
    }
    jj_consume_token(RBRACK);
  }

  static final public void ListaExpressoes() throws ParseException {
    Expressao();
    label_20:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case COMMA:
        ;
        break;
      default:
        jj_la1[57] = jj_gen;
        break label_20;
      }
      jj_consume_token(COMMA);
      Expressao();
    }
  }

/* Regra para ajudar a processar os argumentos separados por virgula */
  static final public void ListaArgumentos() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case MINUS:
    case NOT:
    case MATCH:
    case IF:
    case LPAREN:
    case LBRACK:
    case FALSE:
    case TRUE:
    case CONSTANT:
    case FLOAT_LITERAL:
    case BOOLEAN_LITERAL:
    case CHAR_LITERAL:
    case IDENTIFIER:
    case STRING_LITERAL:
      Expressao();
      label_21:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case COMMA:
          ;
          break;
        default:
          jj_la1[58] = jj_gen;
          break label_21;
        }
        jj_consume_token(COMMA);
        Expressao();
      }
      break;
    default:
      jj_la1[59] = jj_gen;
      ;
    }
  }

  static private boolean jj_2_1(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_1(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(0, xla); }
  }

  static private boolean jj_2_2(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_2(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(1, xla); }
  }

  static private boolean jj_2_3(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_3(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(2, xla); }
  }

  static private boolean jj_2_4(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_4(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(3, xla); }
  }

  static private boolean jj_2_5(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_5(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(4, xla); }
  }

  static private boolean jj_2_6(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_6(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(5, xla); }
  }

  static private boolean jj_2_7(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_7(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(6, xla); }
  }

  static private boolean jj_2_8(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_8(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(7, xla); }
  }

  static private boolean jj_2_9(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_9(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(8, xla); }
  }

  static private boolean jj_2_10(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_10(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(9, xla); }
  }

  static private boolean jj_3R_57() {
    if (jj_3R_59()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_60()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  static private boolean jj_3R_46() {
    if (jj_3R_51()) return true;
    return false;
  }

  static private boolean jj_3R_45() {
    if (jj_3R_50()) return true;
    return false;
  }

  static private boolean jj_3R_39() {
    if (jj_scan_token(CONST)) return true;
    if (jj_scan_token(IDENTIFIER)) return true;
    return false;
  }

  static private boolean jj_3R_44() {
    if (jj_3R_49()) return true;
    return false;
  }

  static private boolean jj_3R_43() {
    if (jj_3R_48()) return true;
    return false;
  }

  static private boolean jj_3R_40() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_42()) {
    jj_scanpos = xsp;
    if (jj_3R_43()) {
    jj_scanpos = xsp;
    if (jj_3R_44()) {
    jj_scanpos = xsp;
    if (jj_3R_45()) {
    jj_scanpos = xsp;
    if (jj_3R_46()) return true;
    }
    }
    }
    }
    return false;
  }

  static private boolean jj_3R_42() {
    if (jj_3R_28()) return true;
    return false;
  }

  static private boolean jj_3R_55() {
    if (jj_3R_57()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_58()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  static private boolean jj_3R_38() {
    if (jj_scan_token(LET)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(27)) jj_scanpos = xsp;
    if (jj_scan_token(IDENTIFIER)) return true;
    return false;
  }

  static private boolean jj_3_6() {
    if (jj_3R_26()) return true;
    return false;
  }

  static private boolean jj_3R_52() {
    if (jj_3R_55()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_56()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  static private boolean jj_3R_54() {
    if (jj_scan_token(LBRACE)) return true;
    return false;
  }

  static private boolean jj_3R_30() {
    if (jj_scan_token(COMMA)) return true;
    return false;
  }

  static private boolean jj_3R_47() {
    if (jj_3R_52()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_53()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  static private boolean jj_3R_41() {
    if (jj_3R_47()) return true;
    return false;
  }

  static private boolean jj_3R_78() {
    if (jj_3R_79()) return true;
    return false;
  }

  static private boolean jj_3_8() {
    if (jj_scan_token(IDENTIFIER)) return true;
    if (jj_scan_token(ASSIGN)) return true;
    return false;
  }

  static private boolean jj_3R_37() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_8()) {
    jj_scanpos = xsp;
    if (jj_3R_41()) return true;
    }
    return false;
  }

  static private boolean jj_3R_29() {
    if (jj_3R_37()) return true;
    return false;
  }

  static private boolean jj_3R_79() {
    if (jj_3R_29()) return true;
    return false;
  }

  static private boolean jj_3R_77() {
    if (jj_scan_token(LBRACK)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_78()) jj_scanpos = xsp;
    if (jj_scan_token(RBRACK)) return true;
    return false;
  }

  static private boolean jj_3R_24() {
    if (jj_scan_token(ENUM)) return true;
    if (jj_scan_token(IDENTIFIER)) return true;
    return false;
  }

  static private boolean jj_3_4() {
    if (jj_3R_25()) return true;
    return false;
  }

  static private boolean jj_3_3() {
    if (jj_3R_24()) return true;
    return false;
  }

  static private boolean jj_3R_76() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(97)) {
    jj_scanpos = xsp;
    if (jj_scan_token(98)) {
    jj_scanpos = xsp;
    if (jj_scan_token(99)) {
    jj_scanpos = xsp;
    if (jj_scan_token(57)) {
    jj_scanpos = xsp;
    if (jj_scan_token(56)) {
    jj_scanpos = xsp;
    if (jj_scan_token(100)) {
    jj_scanpos = xsp;
    if (jj_scan_token(103)) return true;
    }
    }
    }
    }
    }
    }
    return false;
  }

  static private boolean jj_3_2() {
    if (jj_3R_23()) return true;
    return false;
  }

  static private boolean jj_3_1() {
    if (jj_3R_22()) return true;
    return false;
  }

  static private boolean jj_3R_73() {
    if (jj_3R_77()) return true;
    return false;
  }

  static private boolean jj_3R_72() {
    if (jj_scan_token(LPAREN)) return true;
    if (jj_3R_29()) return true;
    return false;
  }

  static private boolean jj_3_10() {
    if (jj_scan_token(LPAREN)) return true;
    if (jj_3R_29()) return true;
    Token xsp;
    if (jj_3R_30()) return true;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_30()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  static private boolean jj_3R_25() {
    if (jj_scan_token(MOD)) return true;
    if (jj_scan_token(IDENTIFIER)) return true;
    return false;
  }

  static private boolean jj_3R_71() {
    if (jj_3R_51()) return true;
    return false;
  }

  static private boolean jj_3R_23() {
    if (jj_scan_token(STRUCT)) return true;
    if (jj_scan_token(IDENTIFIER)) return true;
    return false;
  }

  static private boolean jj_3_9() {
    if (jj_3R_28()) return true;
    return false;
  }

  static private boolean jj_3R_70() {
    if (jj_3R_76()) return true;
    return false;
  }

  static private boolean jj_3R_68() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_70()) {
    jj_scanpos = xsp;
    if (jj_scan_token(102)) {
    jj_scanpos = xsp;
    if (jj_3_9()) {
    jj_scanpos = xsp;
    if (jj_3R_71()) {
    jj_scanpos = xsp;
    if (jj_3_10()) {
    jj_scanpos = xsp;
    if (jj_3R_72()) {
    jj_scanpos = xsp;
    if (jj_3R_73()) return true;
    }
    }
    }
    }
    }
    }
    return false;
  }

  static private boolean jj_3R_36() {
    if (jj_scan_token(READ)) return true;
    if (jj_scan_token(LPAREN)) return true;
    return false;
  }

  static private boolean jj_3R_62() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(5)) {
    jj_scanpos = xsp;
    if (jj_scan_token(6)) return true;
    }
    return false;
  }

  static private boolean jj_3R_51() {
    if (jj_scan_token(MATCH)) return true;
    if (jj_3R_29()) return true;
    return false;
  }

  static private boolean jj_3R_27() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_35()) {
    jj_scanpos = xsp;
    if (jj_3R_36()) return true;
    }
    return false;
  }

  static private boolean jj_3R_35() {
    if (jj_scan_token(PRINT)) return true;
    if (jj_scan_token(LPAREN)) return true;
    return false;
  }

  static private boolean jj_3R_75() {
    if (jj_scan_token(DOT)) return true;
    return false;
  }

  static private boolean jj_3R_64() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(7)) {
    jj_scanpos = xsp;
    if (jj_scan_token(8)) {
    jj_scanpos = xsp;
    if (jj_scan_token(9)) return true;
    }
    }
    return false;
  }

  static private boolean jj_3R_74() {
    if (jj_scan_token(LPAREN)) return true;
    return false;
  }

  static private boolean jj_3R_69() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_74()) {
    jj_scanpos = xsp;
    if (jj_3R_75()) return true;
    }
    return false;
  }

  static private boolean jj_3R_50() {
    if (jj_scan_token(FOR)) return true;
    if (jj_scan_token(IDENTIFIER)) return true;
    return false;
  }

  static private boolean jj_3R_67() {
    if (jj_3R_68()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_69()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  static private boolean jj_3R_22() {
    if (jj_scan_token(FN)) return true;
    if (jj_scan_token(IDENTIFIER)) return true;
    return false;
  }

  static private boolean jj_3R_60() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(15)) {
    jj_scanpos = xsp;
    if (jj_scan_token(16)) {
    jj_scanpos = xsp;
    if (jj_scan_token(17)) {
    jj_scanpos = xsp;
    if (jj_scan_token(18)) return true;
    }
    }
    }
    return false;
  }

  static private boolean jj_3R_49() {
    if (jj_scan_token(LOOP)) return true;
    if (jj_3R_54()) return true;
    return false;
  }

  static private boolean jj_3R_66() {
    if (jj_3R_67()) return true;
    return false;
  }

  static private boolean jj_3R_65() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(6)) {
    jj_scanpos = xsp;
    if (jj_scan_token(12)) return true;
    }
    if (jj_3R_63()) return true;
    return false;
  }

  static private boolean jj_3R_63() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_65()) {
    jj_scanpos = xsp;
    if (jj_3R_66()) return true;
    }
    return false;
  }

  static private boolean jj_3R_58() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(13)) {
    jj_scanpos = xsp;
    if (jj_scan_token(14)) return true;
    }
    return false;
  }

  static private boolean jj_3R_48() {
    if (jj_scan_token(WHILE)) return true;
    if (jj_3R_29()) return true;
    return false;
  }

  static private boolean jj_3R_61() {
    if (jj_3R_63()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_64()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  static private boolean jj_3R_56() {
    if (jj_scan_token(AND)) return true;
    return false;
  }

  static private boolean jj_3_5() {
    if (jj_scan_token(ELSE)) return true;
    if (jj_scan_token(IF)) return true;
    return false;
  }

  static private boolean jj_3R_34() {
    if (jj_3R_29()) return true;
    if (jj_scan_token(SEMICOLON)) return true;
    return false;
  }

  static private boolean jj_3R_59() {
    if (jj_3R_61()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_62()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  static private boolean jj_3_7() {
    if (jj_3R_27()) return true;
    return false;
  }

  static private boolean jj_3R_53() {
    if (jj_scan_token(OR)) return true;
    return false;
  }

  static private boolean jj_3R_33() {
    if (jj_3R_40()) return true;
    return false;
  }

  static private boolean jj_3R_28() {
    if (jj_scan_token(IF)) return true;
    if (jj_3R_29()) return true;
    return false;
  }

  static private boolean jj_3R_32() {
    if (jj_3R_39()) return true;
    return false;
  }

  static private boolean jj_3R_26() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_31()) {
    jj_scanpos = xsp;
    if (jj_3R_32()) {
    jj_scanpos = xsp;
    if (jj_3R_33()) {
    jj_scanpos = xsp;
    if (jj_3_7()) {
    jj_scanpos = xsp;
    if (jj_3R_34()) return true;
    }
    }
    }
    }
    return false;
  }

  static private boolean jj_3R_31() {
    if (jj_3R_38()) return true;
    return false;
  }

  static private boolean jj_initialized_once = false;
  /** Generated Token Manager. */
  static public RustTokenManager token_source;
  static SimpleCharStream jj_input_stream;
  /** Current token. */
  static public Token token;
  /** Next token. */
  static public Token jj_nt;
  static private int jj_ntk;
  static private Token jj_scanpos, jj_lastpos;
  static private int jj_la;
  /** Whether we are looking ahead. */
  static private boolean jj_lookingAhead = false;
  static private boolean jj_semLA;
  static private int jj_gen;
  static final private int[] jj_la1 = new int[60];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static private int[] jj_la1_2;
  static private int[] jj_la1_3;
  static {
      jj_la1_init_0();
      jj_la1_init_1();
      jj_la1_init_2();
      jj_la1_init_3();
   }
   private static void jj_la1_init_0() {
      jj_la1_0 = new int[] {0x2000000,0x0,0x2000000,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0xb0000000,0x40000000,0x0,0x0,0x0,0x30001040,0x0,0x30001040,0x8000000,0x0,0x0,0xb4000000,0x30001040,0x0,0x1f00000,0x1f00000,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x30001040,0x800,0x400,0x6000,0x6000,0x78000,0x78000,0x60,0x60,0x380,0x380,0x1040,0x30001040,0x80000,0x0,0x80000,0x0,0x0,0x10000000,0x0,0x0,0x30001040,0x0,0x0,0x30001040,};
   }
   private static void jj_la1_init_1() {
      jj_la1_1 = new int[] {0x20086000,0x0,0x20086000,0x80000,0x0,0x200,0x8000,0x20,0x20,0x0,0x10000001,0x0,0x3000000,0x200,0x3000000,0x30008a0,0x0,0x3000880,0x0,0x10,0x4,0x10080001,0x3000880,0x200,0x880,0x0,0x0,0x2,0x200,0x0,0x200,0x200,0x0,0x200,0x200,0x3000880,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x3000880,0x80,0x80,0x80,0x200,0x3000000,0x0,0x880,0x3000000,0x3000880,0x200,0x200,0x3000880,};
   }
   private static void jj_la1_init_2() {
      jj_la1_2 = new int[] {0x200,0x0,0x200,0x200,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x40000000,0x0,0x40000000,0x0,0x80000000,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,};
   }
   private static void jj_la1_init_3() {
      jj_la1_3 = new int[] {0x0,0x300,0x0,0x0,0x40,0x0,0x0,0x40,0x40,0x1,0x0,0x0,0xca,0x0,0xca,0xde,0x0,0xde,0x0,0x0,0x0,0x0,0xde,0x0,0x0,0x0,0x40,0x0,0x0,0x40,0x0,0x0,0x40,0x0,0x0,0xde,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0xde,0x0,0x0,0x0,0x0,0xde,0x0,0x0,0x9e,0xde,0x0,0x0,0xde,};
   }
  static final private JJCalls[] jj_2_rtns = new JJCalls[10];
  static private boolean jj_rescan = false;
  static private int jj_gc = 0;

  /** Constructor with InputStream. */
  public Rust(java.io.InputStream stream) {
     this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public Rust(java.io.InputStream stream, String encoding) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser.  ");
      System.out.println("       You must either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source = new RustTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 60; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream) {
     ReInit(stream, null);
  }
  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream, String encoding) {
    try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 60; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor. */
  public Rust(java.io.Reader stream) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser. ");
      System.out.println("       You must either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    jj_input_stream = new SimpleCharStream(stream, 1, 1);
    token_source = new RustTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 60; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  static public void ReInit(java.io.Reader stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 60; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor with generated Token Manager. */
  public Rust(RustTokenManager tm) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser. ");
      System.out.println("       You must either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 60; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(RustTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 60; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  static private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      if (++jj_gc > 100) {
        jj_gc = 0;
        for (int i = 0; i < jj_2_rtns.length; i++) {
          JJCalls c = jj_2_rtns[i];
          while (c != null) {
            if (c.gen < jj_gen) c.first = null;
            c = c.next;
          }
        }
      }
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }

  static private final class LookaheadSuccess extends java.lang.Error { }
  static final private LookaheadSuccess jj_ls = new LookaheadSuccess();
  static private boolean jj_scan_token(int kind) {
    if (jj_scanpos == jj_lastpos) {
      jj_la--;
      if (jj_scanpos.next == null) {
        jj_lastpos = jj_scanpos = jj_scanpos.next = token_source.getNextToken();
      } else {
        jj_lastpos = jj_scanpos = jj_scanpos.next;
      }
    } else {
      jj_scanpos = jj_scanpos.next;
    }
    if (jj_rescan) {
      int i = 0; Token tok = token;
      while (tok != null && tok != jj_scanpos) { i++; tok = tok.next; }
      if (tok != null) jj_add_error_token(kind, i);
    }
    if (jj_scanpos.kind != kind) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) throw jj_ls;
    return false;
  }


/** Get the next Token. */
  static final public Token getNextToken() {
    if (token.next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
    return token;
  }

/** Get the specific Token. */
  static final public Token getToken(int index) {
    Token t = jj_lookingAhead ? jj_scanpos : token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = token_source.getNextToken();
    }
    return t;
  }

  static private int jj_ntk() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  static private java.util.List jj_expentries = new java.util.ArrayList();
  static private int[] jj_expentry;
  static private int jj_kind = -1;
  static private int[] jj_lasttokens = new int[100];
  static private int jj_endpos;

  static private void jj_add_error_token(int kind, int pos) {
    if (pos >= 100) return;
    if (pos == jj_endpos + 1) {
      jj_lasttokens[jj_endpos++] = kind;
    } else if (jj_endpos != 0) {
      jj_expentry = new int[jj_endpos];
      for (int i = 0; i < jj_endpos; i++) {
        jj_expentry[i] = jj_lasttokens[i];
      }
      boolean exists = false;
      for (java.util.Iterator it = jj_expentries.iterator(); it.hasNext();) {
        int[] oldentry = (int[])(it.next());
        if (oldentry.length == jj_expentry.length) {
          exists = true;
          for (int i = 0; i < jj_expentry.length; i++) {
            if (oldentry[i] != jj_expentry[i]) {
              exists = false;
              break;
            }
          }
          if (exists) break;
        }
      }
      if (!exists) jj_expentries.add(jj_expentry);
      if (pos != 0) jj_lasttokens[(jj_endpos = pos) - 1] = kind;
    }
  }

  /** Generate ParseException. */
  static public ParseException generateParseException() {
    jj_expentries.clear();
    boolean[] la1tokens = new boolean[106];
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 60; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
          if ((jj_la1_1[i] & (1<<j)) != 0) {
            la1tokens[32+j] = true;
          }
          if ((jj_la1_2[i] & (1<<j)) != 0) {
            la1tokens[64+j] = true;
          }
          if ((jj_la1_3[i] & (1<<j)) != 0) {
            la1tokens[96+j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 106; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.add(jj_expentry);
      }
    }
    jj_endpos = 0;
    jj_rescan_token();
    jj_add_error_token(0, 0);
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = (int[])jj_expentries.get(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  /** Enable tracing. */
  static final public void enable_tracing() {
  }

  /** Disable tracing. */
  static final public void disable_tracing() {
  }

  static private void jj_rescan_token() {
    jj_rescan = true;
    for (int i = 0; i < 10; i++) {
    try {
      JJCalls p = jj_2_rtns[i];
      do {
        if (p.gen > jj_gen) {
          jj_la = p.arg; jj_lastpos = jj_scanpos = p.first;
          switch (i) {
            case 0: jj_3_1(); break;
            case 1: jj_3_2(); break;
            case 2: jj_3_3(); break;
            case 3: jj_3_4(); break;
            case 4: jj_3_5(); break;
            case 5: jj_3_6(); break;
            case 6: jj_3_7(); break;
            case 7: jj_3_8(); break;
            case 8: jj_3_9(); break;
            case 9: jj_3_10(); break;
          }
        }
        p = p.next;
      } while (p != null);
      } catch(LookaheadSuccess ls) { }
    }
    jj_rescan = false;
  }

  static private void jj_save(int index, int xla) {
    JJCalls p = jj_2_rtns[index];
    while (p.gen > jj_gen) {
      if (p.next == null) { p = p.next = new JJCalls(); break; }
      p = p.next;
    }
    p.gen = jj_gen + xla - jj_la; p.first = token; p.arg = xla;
  }

  static final class JJCalls {
    int gen;
    Token first;
    int arg;
    JJCalls next;
  }

}
