/* Generated By:JavaCC: Do not edit this line. RustConstants.java */
package projeto_compilador_rust;


/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface RustConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int PLUS = 5;
  /** RegularExpression Id. */
  int MINUS = 6;
  /** RegularExpression Id. */
  int MULTIPLY = 7;
  /** RegularExpression Id. */
  int DIVIDE = 8;
  /** RegularExpression Id. */
  int MODULO = 9;
  /** RegularExpression Id. */
  int AND = 10;
  /** RegularExpression Id. */
  int OR = 11;
  /** RegularExpression Id. */
  int NOT = 12;
  /** RegularExpression Id. */
  int EQ = 13;
  /** RegularExpression Id. */
  int NEQ = 14;
  /** RegularExpression Id. */
  int LT = 15;
  /** RegularExpression Id. */
  int GT = 16;
  /** RegularExpression Id. */
  int LE = 17;
  /** RegularExpression Id. */
  int GE = 18;
  /** RegularExpression Id. */
  int DOT = 19;
  /** RegularExpression Id. */
  int I32 = 20;
  /** RegularExpression Id. */
  int F64 = 21;
  /** RegularExpression Id. */
  int BOOL = 22;
  /** RegularExpression Id. */
  int CHAR_T = 23;
  /** RegularExpression Id. */
  int STR_T = 24;
  /** RegularExpression Id. */
  int FN = 25;
  /** RegularExpression Id. */
  int LET = 26;
  /** RegularExpression Id. */
  int MUT = 27;
  /** RegularExpression Id. */
  int MATCH = 28;
  /** RegularExpression Id. */
  int IF = 29;
  /** RegularExpression Id. */
  int ELSE = 30;
  /** RegularExpression Id. */
  int WHILE = 31;
  /** RegularExpression Id. */
  int FOR = 32;
  /** RegularExpression Id. */
  int ARROW = 33;
  /** RegularExpression Id. */
  int ASSIGN = 34;
  /** RegularExpression Id. */
  int SEMICOLON = 35;
  /** RegularExpression Id. */
  int COLON = 36;
  /** RegularExpression Id. */
  int LBRACE = 37;
  /** RegularExpression Id. */
  int RBRACE = 38;
  /** RegularExpression Id. */
  int LPAREN = 39;
  /** RegularExpression Id. */
  int RPAREN = 40;
  /** RegularExpression Id. */
  int COMMA = 41;
  /** RegularExpression Id. */
  int FAT_ARROW = 42;
  /** RegularExpression Id. */
  int LBRACK = 43;
  /** RegularExpression Id. */
  int RBRACK = 44;
  /** RegularExpression Id. */
  int ENUM = 45;
  /** RegularExpression Id. */
  int STRUCT = 46;
  /** RegularExpression Id. */
  int AS = 47;
  /** RegularExpression Id. */
  int ASYNC = 48;
  /** RegularExpression Id. */
  int AWAIT = 49;
  /** RegularExpression Id. */
  int BREAK = 50;
  /** RegularExpression Id. */
  int CONST = 51;
  /** RegularExpression Id. */
  int CONTINUE = 52;
  /** RegularExpression Id. */
  int CRATE = 53;
  /** RegularExpression Id. */
  int DYN = 54;
  /** RegularExpression Id. */
  int EXTERN = 55;
  /** RegularExpression Id. */
  int FALSE = 56;
  /** RegularExpression Id. */
  int TRUE = 57;
  /** RegularExpression Id. */
  int IMPL = 58;
  /** RegularExpression Id. */
  int IN = 59;
  /** RegularExpression Id. */
  int LOOP = 60;
  /** RegularExpression Id. */
  int MOD = 61;
  /** RegularExpression Id. */
  int MOV = 62;
  /** RegularExpression Id. */
  int PUB = 63;
  /** RegularExpression Id. */
  int REF = 64;
  /** RegularExpression Id. */
  int RETURN = 65;
  /** RegularExpression Id. */
  int SELF = 66;
  /** RegularExpression Id. */
  int SSELF = 67;
  /** RegularExpression Id. */
  int STATIC = 68;
  /** RegularExpression Id. */
  int SUPER = 69;
  /** RegularExpression Id. */
  int TRAIT = 70;
  /** RegularExpression Id. */
  int TYPE = 71;
  /** RegularExpression Id. */
  int UNSAFE = 72;
  /** RegularExpression Id. */
  int USE = 73;
  /** RegularExpression Id. */
  int WHERE = 74;
  /** RegularExpression Id. */
  int ABSTRACT = 75;
  /** RegularExpression Id. */
  int BECOME = 76;
  /** RegularExpression Id. */
  int BOX = 77;
  /** RegularExpression Id. */
  int DO = 78;
  /** RegularExpression Id. */
  int FINAL = 79;
  /** RegularExpression Id. */
  int GEN = 80;
  /** RegularExpression Id. */
  int MACRO = 81;
  /** RegularExpression Id. */
  int OVERRIDE = 82;
  /** RegularExpression Id. */
  int PRIV = 83;
  /** RegularExpression Id. */
  int TRY = 84;
  /** RegularExpression Id. */
  int TYPEOF = 85;
  /** RegularExpression Id. */
  int UNSIZED = 86;
  /** RegularExpression Id. */
  int VIRTUAL = 87;
  /** RegularExpression Id. */
  int YIELD = 88;
  /** RegularExpression Id. */
  int _STATIC = 89;
  /** RegularExpression Id. */
  int MACRO_RULES = 90;
  /** RegularExpression Id. */
  int RAW = 91;
  /** RegularExpression Id. */
  int SAFE = 92;
  /** RegularExpression Id. */
  int UNION = 93;
  /** RegularExpression Id. */
  int UNDERSCORE = 94;
  /** RegularExpression Id. */
  int DOTDOT = 95;
  /** RegularExpression Id. */
  int PATH_SEPARATOR = 96;
  /** RegularExpression Id. */
  int CONSTANT = 97;
  /** RegularExpression Id. */
  int FLOAT_LITERAL = 98;
  /** RegularExpression Id. */
  int BOOLEAN_LITERAL = 99;
  /** RegularExpression Id. */
  int CHAR_LITERAL = 100;
  /** RegularExpression Id. */
  int DIGIT = 101;
  /** RegularExpression Id. */
  int IDENTIFIER = 102;
  /** RegularExpression Id. */
  int STRING_LITERAL = 103;
  /** RegularExpression Id. */
  int PRINT = 104;
  /** RegularExpression Id. */
  int READ = 105;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"&&\"",
    "\"||\"",
    "\"!\"",
    "\"==\"",
    "\"!=\"",
    "\"<\"",
    "\">\"",
    "\"<=\"",
    "\">=\"",
    "\".\"",
    "\"i32\"",
    "\"f64\"",
    "\"bool\"",
    "\"char\"",
    "\"str\"",
    "\"fn\"",
    "\"let\"",
    "\"mut\"",
    "\"match\"",
    "\"if\"",
    "\"else\"",
    "\"while\"",
    "\"for\"",
    "\"->\"",
    "\"=\"",
    "\";\"",
    "\":\"",
    "\"{\"",
    "\"}\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\"=>\"",
    "\"[\"",
    "\"]\"",
    "\"enum\"",
    "\"struct\"",
    "\"as\"",
    "\"async\"",
    "\"await\"",
    "\"break\"",
    "\"const\"",
    "\"continue\"",
    "\"crate\"",
    "\"dyn\"",
    "\"extern\"",
    "\"false\"",
    "\"true\"",
    "\"impl\"",
    "\"in\"",
    "\"loop\"",
    "\"mod\"",
    "\"mov\"",
    "\"pub\"",
    "\"ref\"",
    "\"return\"",
    "\"self\"",
    "\"Self\"",
    "\"static\"",
    "\"super\"",
    "\"trait\"",
    "\"type\"",
    "\"unsafe\"",
    "\"use\"",
    "\"where\"",
    "\"abstract\"",
    "\"become\"",
    "\"box\"",
    "\"do\"",
    "\"final\"",
    "\"gen\"",
    "\"macro\"",
    "\"override\"",
    "\"priv\"",
    "\"try\"",
    "\"typeof\"",
    "\"unsized\"",
    "\"virtual\"",
    "\"yield\"",
    "\"\\\'static\"",
    "\"macro_rules\"",
    "\"raw\"",
    "\"safe\"",
    "\"union\"",
    "\"_\"",
    "\"..\"",
    "\"::\"",
    "<CONSTANT>",
    "<FLOAT_LITERAL>",
    "<BOOLEAN_LITERAL>",
    "<CHAR_LITERAL>",
    "<DIGIT>",
    "<IDENTIFIER>",
    "<STRING_LITERAL>",
    "\"println!\"",
    "\"read_line!\"",
  };

}
